version: 0.0
os: linux
files:
  # Specify the source and destination files/directories if needed
  # For example:
  - source: /
    destination: /home/ubuntu/Ecommerce-backend-mern-main 

hooks:
  BeforeInstall:
    - location: scripts/before_deploy.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_deploy.sh
      timeout: 300
      runas: root
