version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

  pre_build:
    commands:
      - npm install --legacy-peer-deps

  build:
    commands:
      

artifacts:
  files:
    - build/**/*
    - appspec.yml
    - scripts/**

