version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20             # Specifies the Node.js runtime version
  pre_build:
    commands:
      - npm install --legacy-peer-deps  # Forces npm to install the packages
  build:
    commands:
artifacts:
  files: 
    - '**/*'              # Includes all files and subdirectories from the root directory.
    - 'appspec.yml'          # Includes the appspec.yml file
    - 'scripts/**' 
