version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22

  pre_build:
    commands:
      - npm ci --legacy-peer-deps

  build:
    commands:
      - npm run build
      - ls -la dist

artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - appspec.yml
    - scripts/**
